name: Extract wesker-bot

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download zip
        run: |
          curl -L "https://files.catbox.moe/j0x73e.zip" -o wesker-bot.zip

      - name: Debug zip
        run: |
          file wesker-bot.zip
          unzip -l wesker-bot.zip

      - name: Extract
        run: |
          unzip -o wesker-bot.zip -d temp
          cp -r temp/wesker-bot/* .
          rm -rf temp wesker-bot.zip

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "extract wesker bot"
          git push
