name: Extract wesker-bot.zip

on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: ls -lah

      - name: Check zip
        run: |
          if [ ! -f wesker-bot.zip ]; then
            echo "ZIP NOT FOUND"
            exit 1
          fi

      - name: Extract zip
        run: |
          unzip wesker-bot.zip -d temp
          cp -r temp/* .
          rm -rf temp wesker-bot.zip

      - name: Commit
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "extract wesker bot"
          git push
